### ISSUE TITLE
https://github.com/fog/fog-profitbricks/releases cause error in using this on ubuntu 14.04

### ISSUE THREAD

**Issue by coltzhao** [RightScale-Services-Cookbooks/rsc_ros#10]
new `fog-profitbricks` need higher version of ruby 2.x.x, not 1.9.3

use it under ruby 1.9.3 cause

`/usr/local/bin/ros.rb -t download -c aws -u xxxxxxxxx -p xxxxxxxxx -b kabam-rs-artifacts -f xlate2/xxxxxxxxxx.tgz -d /tmp/xlate2.tgz -r us-west-1, STDOUT:, STDERR:/var/lib/gems/1.9.1/gems/fog-profitbricks-2.0.1/lib/fog/profitbricks.rb:4:in `<top (required)>': undefined local variable or method `__dir__' for main:Object (NameError)`

may want to pin the version of `fog-profitbricks` to 0.0.5

**Comment by cdwilhelm** [comment]
this is fixed in release v0.7.0
